<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKYnCsFH\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKYnCsFH/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKYnCsFH.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKYnCsFH\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKYnCsFH\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KYnCsFH',
    'container.build_id' => 'f7206a66',
    'container.build_time' => 1690406511,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKYnCsFH');
