<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRezH4Ax\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRezH4Ax/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRezH4Ax.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRezH4Ax\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRezH4Ax\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RezH4Ax',
    'container.build_id' => 'e80e6447',
    'container.build_time' => 1690405943,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRezH4Ax');
