<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPKaaUx3\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPKaaUx3/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPKaaUx3.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPKaaUx3\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPKaaUx3\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PKaaUx3',
    'container.build_id' => 'f7c1a91f',
    'container.build_time' => 1690211840,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPKaaUx3');
